name: project_documentation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  fluttertoast: ^8.0.7
  http: ^0.13.3
  double_back_to_close: ^2.0.0
  shimmer: ^2.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.0
  path_provider: ^2.0.2
  tuple: ^2.0.0
  provider: ^6.0.2
  
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_github_edited.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf  

